package com.wf.f1.wfactura1.entities;
// Generated 9/10/2019 05:52:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Certs generated by hbm2java
 */
public class Certs  implements java.io.Serializable {


     private int id;
     private String rfc;
     private String llave;
     private String cer;
     private String clave;
     private String usu;
     private Date alta;
     private Date modifico;
     private int estatus;
     private int idUsuario;
     private Date inicio;
     private Date fin;
     private String noCert;
     private String estatusCer;

    public Certs() {
    }

	
    public Certs(int id, String rfc, String llave, String cer, String clave, Date alta, Date modifico, int estatus, int idUsuario) {
        this.id = id;
        this.rfc = rfc;
        this.llave = llave;
        this.cer = cer;
        this.clave = clave;
        this.alta = alta;
        this.modifico = modifico;
        this.estatus = estatus;
        this.idUsuario = idUsuario;
    }
    public Certs(int id, String rfc, String llave, String cer, String clave, String usu, Date alta, Date modifico, int estatus, int idUsuario, Date inicio, Date fin, String noCert, String estatusCer) {
       this.id = id;
       this.rfc = rfc;
       this.llave = llave;
       this.cer = cer;
       this.clave = clave;
       this.usu = usu;
       this.alta = alta;
       this.modifico = modifico;
       this.estatus = estatus;
       this.idUsuario = idUsuario;
       this.inicio = inicio;
       this.fin = fin;
       this.noCert = noCert;
       this.estatusCer = estatusCer;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getLlave() {
        return this.llave;
    }
    
    public void setLlave(String llave) {
        this.llave = llave;
    }
    public String getCer() {
        return this.cer;
    }
    
    public void setCer(String cer) {
        this.cer = cer;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getUsu() {
        return this.usu;
    }
    
    public void setUsu(String usu) {
        this.usu = usu;
    }
    public Date getAlta() {
        return this.alta;
    }
    
    public void setAlta(Date alta) {
        this.alta = alta;
    }
    public Date getModifico() {
        return this.modifico;
    }
    
    public void setModifico(Date modifico) {
        this.modifico = modifico;
    }
    public int getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(int estatus) {
        this.estatus = estatus;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }
    public String getNoCert() {
        return this.noCert;
    }
    
    public void setNoCert(String noCert) {
        this.noCert = noCert;
    }
    public String getEstatusCer() {
        return this.estatusCer;
    }
    
    public void setEstatusCer(String estatusCer) {
        this.estatusCer = estatusCer;
    }




}


