package com.wf.f1.wfactura1.entities;
// Generated 21/08/2019 02:19:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private int id;
     private int userid;
     private String rfc;
     private Integer facturas;
     private Date periodoini;
     private Date periodofin;
     private Integer status;
     private Date fechacambio;
     private Date inicioPruebasF1;
     private Date finPruebasF1;

    public Permisos() {
    }

	
    public Permisos(int id, int userid, String rfc) {
        this.id = id;
        this.userid = userid;
        this.rfc = rfc;
    }
    public Permisos(int id, int userid, String rfc, Integer facturas, Date periodoini, Date periodofin, Integer status, Date fechacambio, Date inicioPruebasF1, Date finPruebasF1) {
       this.id = id;
       this.userid = userid;
       this.rfc = rfc;
       this.facturas = facturas;
       this.periodoini = periodoini;
       this.periodofin = periodofin;
       this.status = status;
       this.fechacambio = fechacambio;
       this.inicioPruebasF1 = inicioPruebasF1;
       this.finPruebasF1 = finPruebasF1;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public Integer getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Integer facturas) {
        this.facturas = facturas;
    }
    public Date getPeriodoini() {
        return this.periodoini;
    }
    
    public void setPeriodoini(Date periodoini) {
        this.periodoini = periodoini;
    }
    public Date getPeriodofin() {
        return this.periodofin;
    }
    
    public void setPeriodofin(Date periodofin) {
        this.periodofin = periodofin;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getFechacambio() {
        return this.fechacambio;
    }
    
    public void setFechacambio(Date fechacambio) {
        this.fechacambio = fechacambio;
    }
    public Date getInicioPruebasF1() {
        return this.inicioPruebasF1;
    }
    
    public void setInicioPruebasF1(Date inicioPruebasF1) {
        this.inicioPruebasF1 = inicioPruebasF1;
    }
    public Date getFinPruebasF1() {
        return this.finPruebasF1;
    }
    
    public void setFinPruebasF1(Date finPruebasF1) {
        this.finPruebasF1 = finPruebasF1;
    }




}


