package com.wf.f1.wfactura1.entities;
// Generated 21/08/2019 02:19:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String mail;
     private String mail2;
     private String clave;
     private String webpass;
     private String usuario;
     private String nombre;
     private Integer rolId;
     private String telefono;
     private String telefono2;
     private String celular;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String ip;
     private Date ultimoAcceso;
     private Integer estatus;
     private String rfc;
     private String razonSocial;
     private String calle;
     private String next;
     private String nint;
     private String colonia;
     private String municipio;
     private String cp;
     private String estado;
     private String pais;
     private Long ta;

    public Usuario() {
    }

	
    public Usuario(int id) {
        this.id = id;
    }
    public Usuario(int id, String mail, String mail2, String clave, String webpass, String usuario, String nombre, Integer rolId, String telefono, String telefono2, String celular, Date fechaCreacion, Date fechaModificacion, String ip, Date ultimoAcceso, Integer estatus, String rfc, String razonSocial, String calle, String next, String nint, String colonia, String municipio, String cp, String estado, String pais, Long ta) {
       this.id = id;
       this.mail = mail;
       this.mail2 = mail2;
       this.clave = clave;
       this.webpass = webpass;
       this.usuario = usuario;
       this.nombre = nombre;
       this.rolId = rolId;
       this.telefono = telefono;
       this.telefono2 = telefono2;
       this.celular = celular;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.ip = ip;
       this.ultimoAcceso = ultimoAcceso;
       this.estatus = estatus;
       this.rfc = rfc;
       this.razonSocial = razonSocial;
       this.calle = calle;
       this.next = next;
       this.nint = nint;
       this.colonia = colonia;
       this.municipio = municipio;
       this.cp = cp;
       this.estado = estado;
       this.pais = pais;
       this.ta = ta;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getMail2() {
        return this.mail2;
    }
    
    public void setMail2(String mail2) {
        this.mail2 = mail2;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getWebpass() {
        return this.webpass;
    }
    
    public void setWebpass(String webpass) {
        this.webpass = webpass;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getRolId() {
        return this.rolId;
    }
    
    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Date getUltimoAcceso() {
        return this.ultimoAcceso;
    }
    
    public void setUltimoAcceso(Date ultimoAcceso) {
        this.ultimoAcceso = ultimoAcceso;
    }
    public Integer getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNext() {
        return this.next;
    }
    
    public void setNext(String next) {
        this.next = next;
    }
    public String getNint() {
        return this.nint;
    }
    
    public void setNint(String nint) {
        this.nint = nint;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Long getTa() {
        return this.ta;
    }
    
    public void setTa(Long ta) {
        this.ta = ta;
    }




}


